### ISSUE TITLE
Getting plugin unavailable in query inspector

### ISSUE THREAD

**Issue by mshirman** [pgollangi/firestore-grafana-datasource#7]
**Describe the bug**
Grafana v9.3.2, running on an Ubuntu AWS instance
- Installed the plugin via Grafana CE UI.
- Successfully configured Firestore data  source using GCP service account credentials
- Created new test Dashboard using the new Firestore data source
- Created new panel, selected new Firestore datasource
- Panel shows no data. 
- Query inspector shows the following in the json response

```
Object
request:Object
url:"api/ds/query"
method:"POST"
data:Object
queries:Array[1]
range:Object
from:"1641024000000"
to:"1672559999999"
hideFromInspector:false
response:Object
message:"An error occurred within the plugin"
messageId:"plugin.downstreamError"
statusCode:500
traceID:""
```

OS log shows the following (Grafana log level = debug)

```
logger=secrets.kvstore t=2023-02-21T00:11:50.147991679Z level=debug msg="got secret value" orgId=1 type=datasource namespace=Firestore-backend
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.150593661Z level=debug msg="QueryData called" numQueries=1
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.150980051Z level=debug msg="FirestoreQuery: " EXTRA_VALUE_AT_END="map[CollectionPath:user_events IsCount:false Limit:0 OrderBy:<nil> Select:<nil> Where:<nil>]"
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.151356351Z level=debug msg="Query ready!"
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.402701399Z level=debug msg="panic: interface conversion: interface {} is []float64, not []string"
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.403348915Z level=debug msg=
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.403789611Z level=debug msg="goroutine 33 [running]:"
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.404847291Z level=debug msg="github.com/pgollangi/firestore/pkg/plugin.(*Datasource).query(0xc000126c00?, {0xea3578, 0xc00045c270}, {0x1, {0xc00026e7a0, 0x1e}, 0xc000466200, 0x0, 0xc000126c00}, {{0x13f0448, ...}, ...})"
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.40526078Z level=debug msg="\t/home/runner/work/firestore-grafana-datasource/firestore-grafana-datasource/pkg/plugin/datasource.go:189 +0x1525"
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.40580811Z level=debug msg="github.com/pgollangi/firestore/pkg/plugin.(*Datasource).QueryData(0xc00027d580?, {0xea3578, 0xc00045c270}, 0xc000275cc0)"
logger=plugin.pgollangi-firestore-datasource t=2023-02-21T00:11:50.406305742Z level=debug msg="\t/home/runner/work/firestore-grafana-datasource/firestore-grafana-datasource/pkg/plugin/datasource.go:61 +0x276"

```

**Comment by pgollangi** [comment]
@mshirman thanks for reporting the issue. Could you please share which version of grafana-firestore-datasource plugin you are using?

From the log, I presume you are using v0.1.3. if yes, could you please update to [latest version (0.1.4) ](https://grafana.com/grafana/plugins/pgollangi-firestore-datasource/)and check?

**Comment by pss-datta** [comment]
@pgollangi  We have tried with fireql queries on Grafana on firestore data source with latest version of plugin, repeatedly getting server unavailable issue, when we uninstall and install plugin again system starts working

Grafana version =>Grafana v9.5.2 
Firestore Plugin = > 0.2.3

**Looking forward for solution for this issue**

**LOGS:**
logger=plugin.pgollangi-firestore-datasource t=2023-06-28T10:52:58.552144046Z level=info msg="Created fireql.NewFireQLWithServiceAccountJSON"
logger=plugin.pgollangi-firestore-datasource t=2023-06-28T10:52:58.552226027Z level=info msg="Executing query" EXTRA_VALUE_AT_END="SELECT * FROM users_test"
logger=context userId=1 orgId=1 uname=admin t=2023-06-28T10:52:58.726140531Z level=error msg="Internal server error" error="[plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = Unavailable desc = error reading from server: EOF" remote_addr=103.208.69.169 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-06-28T10:52:58.726280729Z level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=103.208.69.169 time_ms=184 duration=184.522888ms size=116 referer="http://xx.xx.xxx.xxx:3000/d/ee1d6437-76aa-4a09-a26e-da3ae91854f3/firestore-development?editPanel=8&orgId=1" handler=/api/ds/query

logger=context userId=1 orgId=1 uname=admin t=2023-06-28T10:59:25.093890613Z level=error msg="Internal server error" error="[plugin.unavailable] plugin unavailable" remote_addr=103.208.69.169 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-06-28T10:59:25.094015356Z level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=103.208.69.169 time_ms=4 duration=4.282947ms size=98 referer="http://xx.xx.xxx.xxx:3000/dashboard/new?editPanel=1&orgId=1" handler=/api/ds/query
logger=context userId=1 orgId=1 uname=admin t=2023-06-28T10:59:27.202910536Z level=error msg="Internal server error" error="[plugin.unavailable] plugin unavailable" remote_addr=103.208.69.169 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-06-28T10:59:27.203032303Z level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=103.208.69.169 time_ms=1 duration=1.179439ms size=98 referer="http://xx.xx.xxx.xxx:3000/dashboard/new?editPanel=1&orgId=1" handler=/api/ds/query
logger=context userId=1 orgId=1 uname=admin t=2023-06-28T10:59:33.467046423Z level=error msg="Internal server error" error="[plugin.unavailable] plugin unavailable" remote_addr=103.208.69.169 traceID=
ry status=500 remote_addr=1xx.xx.xxx.xxx time_ms=184 duration=184.522888ms size=116 referer="http://xx.xx.xxx.xxx:3000/d/ee1d6437-76aa-4a09-a26e-da3ae91854f3/firestore-development?editPanel=8&orgId=1" handler=/api/ds/query
